### ISSUE TITLE
Split into two WGs?

### ISSUE THREAD

**Issue by jmertic** [carbon-data-specification/.github#10]
Split of work:

- WG1 - Connectivity
- WG3 - Customer Data (new)

**Comment by daniel-utilityapi** [comment]
The split is now complete:
https://connectivity.carbondataspec.org/
https://customerdata.carbondataspec.org/

**Comment by halliecramer1** [comment]
- Two separate mailing lists, in opendev, need to update calendars per working groups

**Comment by jmertic** [comment]
We have a public calendar for all CDSC public meetings at https://calendar.carbondataspec.org/

WG3 mailing list at https://lists.lfenergy.org/g/cdsc-connectivity-wg
