### ISSUE TITLE
LFESS Blogs

### ISSUE THREAD

**Issue by jmertic** [carbon-data-specification/.github#4]
Two blogs:

1.  Thought leadership blog authored by Alex Thornton on the importance of standards and LFESS
2. Announcement blog post of the DRAFT specs

**Comment by jmertic** [comment]
@jmertic To check with Alex again on this.

**Comment by jmertic** [comment]
For (1), the Plan currently is to post this week of 6/24.

@dbrownlf — @halliecramer1 asked if it makes more sense to have the blog post before #5 or after. Thoughts?

For (2), @daniel-utilityapi requested to announce after the #10 is completed.

**Comment by dbrownlf** [comment]
@jmertic @halliecramer1 Alex is going to try to get this done sooner than planned. If so, we can post it before the webinar and also use the post to help with promotion.

**Comment by dbrownlf** [comment]
@daniel-utilityapi @jmertic No problem, please keep me updated on progress. It would be helpful as well to have some background on each working group's role/goals that can be incorporated into the announcement if there's anything you can share.

**Comment by halliecramer1** [comment]
Posted at the following link: https://lfenergy.org/how-open-standards-complement-traditional-ones-and-can-speed-the-energy-transition/
