### ISSUE TITLE
CDSC Webinar

### ISSUE THREAD

**Issue by jmertic** [carbon-data-specification/.github#5]
@halliecramer1 to connect with Dan Brown

**Comment by halliecramer1** [comment]
What's needed (to discuss):
* Date/time - I'd suggest early morning Pacific so folks in Europe can join. Note the PowSyBl project just claimed June 3 for a webinar so I'd request we do this June 10 or later, but we can make any date work other than the 3rd. Particularly as we'll be getting into summer I'd advise you to avoid Fridays. Please also note the duration you want; we do advise leaving some time for Q&A.
* Webinar title
* Description - I'd advise keeping this to no more than 3-4 paragraphs. If there will be multiple sections and/or speakers, you can also provide an agenda.
* Names, titles, companies, bios, emails, and headshots for whoever will present (you can also add a Twitter/X handle optionally for any speakers who want to list that, the system does not support other social media links such as LinkedIn unfortunately).

**Comment by jmertic** [comment]
Feedback during CDSC Community Call today:

- Webinar should be a tour of the WGs and specs, and how to get involved/contribute.
- Maybe split into two webinars; one for each WG? Concern is webinars combined could get quite long.
- Or, perhaps one webinar and then move into breakout rooms?

@halliecramer1 to take first pass at structure and agenda, and share in this issue. Will then follow up on scheduling.

**Comment by halliecramer1** [comment]
Registration link here: https://community.linuxfoundation.org/events/details/lfhq-lf-energy-presents-carbon-data-specifications-mechanisms-to-improve-data-accessstandardization-in-the-energy-industry/

Create or amplify LinkedIn post here: https://www.linkedin.com/posts/hallie-cramer_carbon-data-specifications-mechanisms-to-activity-7204158925393256450-1gWS

**Comment by jmertic** [comment]
Happening on 6/20

**Comment by halliecramer1** [comment]
Link to webinar for future reference: https://community.linuxfoundation.org/events/details/lfhq-lf-energy-presents-carbon-data-specifications-mechanisms-to-improve-data-accessstandardization-in-the-energy-industry/
